### ISSUE TITLE
Where is IntelliJ IDEA code style XML or Eclipse XML Profile?

### ISSUE THREAD

**Issue by humengyu2012** [apache/seatunnel#1487]
We have enabled code style checking: https://github.com/apache/incubator-seatunnel/blob/dev/tools/checkstyle/checkStyle.xml, but where is the xml profile? Manual compatibility code format is difficult and not friendly for developers.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/45056332/158243389-805fd2d2-741d-4936-b52e-11d401382975.png">

**Comment by Hisoka-X** [comment]
In `/incubator-seatunnel/tools/checkstyle` folder, should install checkstyle plugin in idea. But have some problem with checkStyle.xml. Need somebody fix it.

**Comment by kezhenxu94** [comment]
@humengyu2012 you didn't install the checkstyle plugin, this file https://github.com/apache/incubator-seatunnel/blob/dev/tools/checkstyle/checkStyle.xml is checkstyle configuration format but you import it as IntelliJ code style, it is definitely wrong, if you installed checkstyle plugin, you should have this menu item 

<img width="411" alt="image" src="https://user-images.githubusercontent.com/15965696/158307464-b7b9938e-9373-48ec-924f-cf22283809dd.png">

**Comment by CalvinKirs** [comment]
Since you don't have a clear context it's hard for me to tell, but #1490 is a known issue. @BenJFan 
But we need to be able to provide clear documentation at best

**Comment by tisonkun** [comment]
I second @kezhenxu94 's suggestion. One more point is that the default version of IDEA checkstyle plugin is 10.0 which is incompatible with seatunnel's setting.

@CalvinKirs I suggest seatunnel config checkstyle version explicitly in `pom.xml` so that it's fixed and easy to find for contributors.

But all in all, the default version of checkstyle of maven-checkstyle-plugin 3.1.0 is 8.19. And I've tested with 8.20.

It seems #1490 will upgrade to 3.1.2 and the default version of checkstyle becomes 8.29.

See also https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html.

**Comment by Hisoka-X** [comment]
> Since you don't have a clear context it's hard for me to tell, but #1490 is a known issue. @BenJFan But we need to be able to provide clear documentation at best

Developer guide need rewrite.

**Comment by humengyu2012** [comment]
I use checkstyle plugin instead of idea profile, it works. Thanks.
