### ISSUE TITLE
[Feature]Support JDK 11 compiling

### ISSUE THREAD

**Issue by CalvinKirs** [apache/seatunnel#1552]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hi all @apache/seatunnel-committers

According to the OpenJDK website(https://adoptopenjdk.net/support.html), there are 3 TLS versions for now

Java 8 (LTS). At Least May 2026
Java 11 (LTS). At Least Oct 2024
Java 17(LTS) TBC[1]
We should make the JDK11 compiling passed. That is the primary agenda when I started this suggestion. 
Also, If you have any concerns, please reply.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Great! I think we should compile java 11 and thanks Calvin bring this up

**Comment by zhongjiajie** [comment]
> Great! I think we should compile java 11.

**Comment by ruanwenjun** [comment]
I tested in jdk11, it failed with `scala-maven-plugin` execute failed, this may be related to scala version.

After upgrade scala version to 2.11.12 and add `scala-library`, then build success.
```
<dependency>
         <groupId>org.scala-lang</groupId>
         <artifactId>scala-library</artifactId>
         <version>${scala.version}</version>
</dependency>
```

And do we need to add a `seatunnel-scala` module to put the scala lib, now I put the scala lib in `seatunnel-config-shade` module, since this module will be dependenced by all other module.
