### ISSUE TITLE
[Feature][Dashboard] Visual management interface

### ISSUE THREAD

**Issue by ChenpiDog** [apache/seatunnel#2847]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

It is recommended to provide a visual management interface.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChenpiDog** [comment]
I mean ETL low code platforms, like Kettle.

**Comment by ChenpiDog** [comment]
@ashulin Hello, this issue has not been replied for a long time. Can Roadmap consider this function? This can improve the usability of seatunnel and make it more user friendly.

**Comment by ashulin** [comment]
hi, @ChenpiDog. I'm sorry, The development of the visual interface is currently in progress. You can follow https://github.com/apache/incubator-seatunnel-web

Since I have not paid attention to this submodule, you have to communicate with the maintainers(@dijiekstra @luketalent @zhuangchong @songjianet ) of the web for features and tasks
You can also subscribe dev@seatunnel.apache.org

You are welcome to contribute to Apache SeaTunnel.

**Comment by ChenpiDog** [comment]
> hi, @ChenpiDog. I'm sorry, The development of the visual interface is currently in progress. You can follow https://github.com/apache/incubator-seatunnel-web
> 
> Since I have not paid attention to this submodule, you have to communicate with the maintainers(@dijiekstra @luketalent @zhuangchong @songjianet ) of the web for features and tasks You can also subscribe [dev@seatunnel.apache.org](mailto:dev@seatunnel.apache.org)
> 
> You are welcome to contribute to Apache SeaTunnel.

OK, thanks.
