### ISSUE TITLE
[Feature][transform-v2] add sql plug-in 

### ISSUE THREAD

**Issue by YMBSKLK** [apache/seatunnel#3926]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the process of data transformation, it is often necessary to associate multiple tables. In transformation v1, we can use the flink/spark sql plug-in to achieve this function.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Follow the community plan, ST will be a ELT platform and maybe discard advanced conversion plug-ins such as SQL. cc @EricJoy2048 @CalvinKirs

**Comment by TyrantLucifer** [comment]
> In the process of data transformation, it is often necessary to associate multiple tables. In transformation v1, we can use the flink/spark sql plug-in to achieve this function

BTW, SQL ability depend on Spark or Flink, in order to keep the same features about different engines and community decides not to support SQL plugin in next version 2.3.1. I will close this issue, if you also have any other problems, please send e-mail to dev@seatunnel.apache.org and discuss with community.
