### ISSUE TITLE
JDBC是否支持分库分表

### ISSUE THREAD

**Issue by RoundYuanYuan** [apache/seatunnel#4507]
您好我目前使用的是 2.3.1 版本，请问目前是否支持mysql表的分库分表 场景的同步（非实时场景）？ 如果不支持的话有计划支持吗？

**Comment by laglangyue** [comment]
We support multiple sources, but now it's not that convenient to use databases and tables. You can define multiple sources.

我们是支持多source的,现在分库分表用起来没有那么方便,你可以定义多个source.

besides, please use English next issue.

**Comment by laglangyue** [comment]
in my opinion, more convenient to define sub databases and tables in future.

**Comment by RoundYuanYuan** [comment]
how to config multiple sources? I defined multiple JDBC but writing data to only one table

**Comment by davidzollo** [comment]
@RoundYuanYuan thanks for your issue
As a global project, please update the issue title and description in English, thx

**Comment by davidzollo** [comment]
> how to config multiple sources? I defined multiple JDBC but writing data to only one table

you can config multi sources and multi sinks for now, just take ` FakeSource` and `Console` for an example:
```
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "BATCH"
  #checkpoint.interval = 10000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}


source {
    FakeSource {
      parallelism = 2
      result_table_name = "fake"
      schema = {
      	fields {
        	name = "string"
        	age = "int"
      	}
	}
    }

    FakeSource {
      parallelism = 2
      result_table_name = "fake1"
      schema = {
        fields {
                name = "string"
                age = "int"
        }
        }
    }



}


sink {
    Console {
      source_table_name = "fake"
    }
    Console {
      source_table_name = "fake1"
    }
}
```

**Comment by YOMO-Lee** [comment]
I also have a usage scenario for this sub table. Our development team uses a sub database sub table, and I now need to synchronize the data of the sub table to the data warehouse table, such as table_ 1. Table_ 2. Table_ 3 Three tables are one table in my database. I also see that community personnel recommend configuring multiple data sources, which can only be a temporary method, because I need to maintain this data source list later. I hope to add support scenarios for table splitting, such as using regular matching, so that as long as the Naming convention of table splitting are unified, my source configuration will not be needed
