### ISSUE TITLE
[Feature][LocalFile Source] Can you develop a real-time collection of file components, functions similar to Flume's TailSource

### ISSUE THREAD

**Issue by xiaoVinCode** [apache/seatunnel#5452]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Can you develop a real-time collection of file components, functions similar to Flume's TailSource
可以开发一个实时采集文件的组件吗，功能类似Flume的TailSource

### Usage Scenario

The log file is continuously written, and the data in the log file needs to be collected in real time and sent to Kafka. At present, Flume TailSource is supported and supports resumable transmission.
日志文件不断地写入，需要实时采集日志文件中的数据发送到Kafka，目前Flume的TailSource是支持的，且支持断点续传。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
1. Because synchronization tasks must run on the synchronization engine node, rather than the node where the log files are located, the prerequisite for implementing this function is for the log files to be written to a distributed file system or cloud storage, such as HDFS, OSS, S3, etc.
2. We can extend File Source to support real-time streaming reading of files.

Are you willing to give it a try?
