### ISSUE TITLE
[Feature][Sqlserver-CDC] Add multi-table e2e testcase

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#5678]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Sqlserver-CDC] Add multi-table read e2e testcase

add testcae into 
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e

reference
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mysql-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/cdc/mysql/MysqlCDCIT.java#L177

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
@hailin0  hi, i want to do this

**Comment by davidzollo** [comment]
Reopening this issue because it is still a useful and contributor-friendly gap, and it was closed by stale automation rather than by completed work.

If you'd like to make a first or early contribution to SeaTunnel, this is a warm welcome path to start with. The goal is focused: add a multi-table SQLServer CDC E2E case under the existing SQLServer CDC E2E module and verify the multi-table read path clearly.

Please leave a comment here if you'd like to claim it. Even a small first step is welcome, and we will gladly help clarify the test scope and acceptance expectations. Thank you to everyone who chooses to contribute time and care to the project.

**Comment by davidzollo** [comment]
OK, I'd like to implement it
